# Define name of the GitHub Actions Workflow.
name: Run Tests
# Trigger the GitHub Actions Workflow on push or pull request to the main branch.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
# Create a job named Run Tests running on the latest supported Ubuntu VM.
jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    # Add an environment variable necessary to run our tests.
    env:
      TESTING: true
    # Define steps to run tests
    # from checking out the repo 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
    # setting up python & python virtual environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.6' # Change to your desired Python version

      - name: Setup Python Virtual Environment
        run: python -m venv python3-virtualenv
    # install dependencies, and lastly, run the tests.
      - name: Install Dependencies
        run: python3-virtualenv/bin/pip install -r requirements.txt

      - name: Allows Permissions For Script
        run: chmod u+x run_test.sh

      - name: Run Tests
        run: ./run_test.sh